AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Lambda setup to show if local development is running on AWS as well.


Globals:
  Function:
    Runtime: python3.8
    Timeout: 600
    MemorySize: 1024


Resources:
  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.index.handler
      CodeUri: ./lambda/src
      Description: Test as clean code example.
      Environment:
        Variables:
          LOG_LEVEL: DEBUG
      Policies:
      - Statement:
        - Effect: Allow
          Action:
          - s3:List*
          Resource: '*'
